<Project Sdk="Microsoft.NET.Sdk">

  <!-- Shadow project. See Content.csproj. -->

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Sim</AssemblyName>
    <RootNamespace>RTS.Sim</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../Assets/Sim/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Content/Content.csproj" />
  </ItemGroup>

</Project>
